<?php
namespace Bing\Controller;
use Common\Controller\AlipayBaseController;
use Think\Log;
class AlipayWapController extends AlipayBaseController{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 支付请求
     */
    public function wapPay(){
        $aop = new \AopClient();
        $aop->appId = self::APPID;
        $aop->rsaPrivateKeyFilePath = $this->privatekey;
        $aop->alipayPublicKey = $this->publickey;

        $request= new \AlipayTradeWapPayRequest();
        $request->setNotifyUrl('');
        $orderInfo = array(
            'out_trade_no' => date("YmdHis"),
            'total_amount' =>I('get.total_amount'),
            'subject' =>I('get.subject'),
            'product_code'=>'QUICK_WAP_WAY'
        );
        $request->setBizContent(json_encode($orderInfo));

        $result=$aop->pageExecute($request);
        echo $result;
    }


    /**
     * 回到通知
     */
    public function notfiy(){
        $notfiyData=I("post.");
//        Log::write("回调信息:".var_export($notfiyData,true));
        if($notfiyData['trade_status']=='TRADE_SUCCESS'){
            //交易成功
        }else if($notfiyData['trade_status']=='TRADE_CLOSED'){
            //交易关闭
        }

    }
}